-- begin BSS_QUASAR_PROJECT
alter table BSS_QUASAR_PROJECT add constraint FK_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE foreign key (BUSINESS_TYPE_ID) references BSS_BUSINESS_TYPE(ID)^
create unique index IDX_BSS_QUASAR_PROJECT_UK_PROJECT_NAME on BSS_QUASAR_PROJECT (PROJECT_NAME) where DELETE_TS is null ^
create index IDX_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE on BSS_QUASAR_PROJECT (BUSINESS_TYPE_ID)^
-- end BSS_QUASAR_PROJECT
-- begin BSS_MAIN_DIRECTION
create unique index IDX_BSS_MAIN_DIRECTION_UK_DIRECTION_NAME on BSS_MAIN_DIRECTION (DIRECTION_NAME) where DELETE_TS is null ^
-- end BSS_MAIN_DIRECTION
-- begin BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK
alter table BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_QUAPROQUAPRO_ON_QUASAR_PRODUCT_1 foreign key (QUASAR_PRODUCT_1_ID) references BSS_QUASAR_PRODUCT(ID)^
alter table BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_QUAPROQUAPRO_ON_QUASAR_PRODUCT_2 foreign key (QUASAR_PRODUCT_2_ID) references BSS_QUASAR_PRODUCT(ID)^
-- end BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK
-- begin BSS_COMPETITOR_PRODUCT
alter table BSS_COMPETITOR_PRODUCT add constraint FK_BSS_COMPETITOR_PRODUCT_ON_COMPETITOR foreign key (COMPETITOR_ID) references BSS_COMPETITOR(ID)^
alter table BSS_COMPETITOR_PRODUCT add constraint FK_BSS_COMPETITOR_PRODUCT_ON_PARENT_PRODUCT foreign key (PARENT_PRODUCT_ID) references BSS_COMPETITOR_PRODUCT(ID)^
create index IDX_BSS_COMPETITOR_PRODUCT_ON_COMPETITOR on BSS_COMPETITOR_PRODUCT (COMPETITOR_ID)^
create index IDX_BSS_COMPETITOR_PRODUCT_ON_PARENT_PRODUCT on BSS_COMPETITOR_PRODUCT (PARENT_PRODUCT_ID)^
-- end BSS_COMPETITOR_PRODUCT
-- begin BSS_FEATURE
alter table BSS_FEATURE add constraint FK_BSS_FEATURE_ON_PARENT_FEATURE foreign key (PARENT_FEATURE_ID) references BSS_FEATURE(ID)^
alter table BSS_FEATURE add constraint FK_BSS_FEATURE_ON_PRODUCT foreign key (PRODUCT_ID) references BSS_QUASAR_PRODUCT(ID)^
create index IDX_BSS_FEATURE_ON_PARENT_FEATURE on BSS_FEATURE (PARENT_FEATURE_ID)^
create index IDX_BSS_FEATURE_ON_PRODUCT on BSS_FEATURE (PRODUCT_ID)^
-- end BSS_FEATURE
-- begin BSS_QUASAR_PROJECT_MAIN_DIRECTION_LINK
alter table BSS_QUASAR_PROJECT_MAIN_DIRECTION_LINK add constraint FK_QUAPROMAIDIR_ON_MAIN_DIRECTION foreign key (MAIN_DIRECTION_ID) references BSS_MAIN_DIRECTION(ID)^
alter table BSS_QUASAR_PROJECT_MAIN_DIRECTION_LINK add constraint FK_QUAPROMAIDIR_ON_QUASAR_PROJECT foreign key (QUASAR_PROJECT_ID) references BSS_QUASAR_PROJECT(ID)^
-- end BSS_QUASAR_PROJECT_MAIN_DIRECTION_LINK
-- begin BSS_COMPETITOR_PRODUCT_QUASAR_PRODUCT_LINK
alter table BSS_COMPETITOR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_COMPROQUAPRO_ON_COMPETITOR_PRODUCT foreign key (COMPETITOR_PRODUCT_ID) references BSS_COMPETITOR_PRODUCT(ID)^
alter table BSS_COMPETITOR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_COMPROQUAPRO_ON_QUASAR_PRODUCT foreign key (QUASAR_PRODUCT_ID) references BSS_QUASAR_PRODUCT(ID)^
-- end BSS_COMPETITOR_PRODUCT_QUASAR_PRODUCT_LINK
-- begin BSS_MARKET_SEGMENT
alter table BSS_MARKET_SEGMENT add constraint FK_BSS_MARKET_SEGMENT_ON_BUSINESS_TYPE foreign key (BUSINESS_TYPE_ID) references BSS_BUSINESS_TYPE(ID)^
alter table BSS_MARKET_SEGMENT add constraint FK_BSS_MARKET_SEGMENT_ON_PARENT_SEGMENT foreign key (PARENT_SEGMENT_ID) references BSS_MARKET_SEGMENT(ID)^
create index IDX_BSS_MARKET_SEGMENT_ON_BUSINESS_TYPE on BSS_MARKET_SEGMENT (BUSINESS_TYPE_ID)^
create index IDX_BSS_MARKET_SEGMENT_ON_PARENT_SEGMENT on BSS_MARKET_SEGMENT (PARENT_SEGMENT_ID)^
-- end BSS_MARKET_SEGMENT
-- begin BSS_QUASAR_PRODUCT
alter table BSS_QUASAR_PRODUCT add constraint FK_BSS_QUASAR_PRODUCT_ON_DIRECTION foreign key (DIRECTION_ID) references BSS_MAIN_DIRECTION(ID)^
create index IDX_BSS_QUASAR_PRODUCT_ON_DIRECTION on BSS_QUASAR_PRODUCT (DIRECTION_ID)^
-- end BSS_QUASAR_PRODUCT
-- begin BSS_CONTACTS_CONTACT_KIND_LINK
alter table BSS_CONTACTS_CONTACT_KIND_LINK add constraint FK_CONCONKIN_ON_CONTACTS foreign key (CONTACTS_ID) references BSS_CONTACTS(ID)^
alter table BSS_CONTACTS_CONTACT_KIND_LINK add constraint FK_CONCONKIN_ON_CONTACT_KIND foreign key (CONTACT_KIND_ID) references BSS_CONTACT_KIND(ID)^
-- end BSS_CONTACTS_CONTACT_KIND_LINK

-- begin BSS_GRANT
alter table BSS_GRANT add constraint FK_BSS_GRANT_ON_FUND foreign key (FUND_ID) references BSS_FUND(ID)^
create index IDX_BSS_GRANT_ON_FUND on BSS_GRANT (FUND_ID)^
-- end BSS_GRANT
-- begin BSS_IMPORTED_POST_CODE_1
create unique index IDX_BSS_IMPORTED_POST_CODE_1_UK_POST_INDEX on BSS_IMPORTED_POST_CODE_1 (POST_INDEX) where DELETE_TS is null ^
-- end BSS_IMPORTED_POST_CODE_1
-- begin BSS_EDUCATIONAL_ORGANIZATION
alter table BSS_EDUCATIONAL_ORGANIZATION add constraint FK_BSS_EDUCATIONAL_ORGANIZATION_ON_DIRECTOR foreign key (DIRECTOR_ID) references BSS_CONTACTS(ID)^
alter table BSS_EDUCATIONAL_ORGANIZATION add constraint FK_BSS_EDUCATIONAL_ORGANIZATION_ON_REGION foreign key (REGION_ID) references BSS_REGION(ID)^
alter table BSS_EDUCATIONAL_ORGANIZATION add constraint FK_BSS_EDUCATIONAL_ORGANIZATION_ON_AREA foreign key (AREA_ID) references BSS_AREA(ID)^
alter table BSS_EDUCATIONAL_ORGANIZATION add constraint FK_BSS_EDUCATIONAL_ORGANIZATION_ON_CITY foreign key (CITY_ID) references BSS_CITY(ID)^
alter table BSS_EDUCATIONAL_ORGANIZATION add constraint FK_BSS_EDUCATIONAL_ORGANIZATION_ON_SUB_CITY foreign key (SUB_CITY_ID) references BSS_SUB_CITY(ID)^
create unique index IDX_BSS_EDUCATIONAL_ORGANIZATION_UK_SCHOOL_GUID on BSS_EDUCATIONAL_ORGANIZATION (SCHOOL_GUID) where DELETE_TS is null ^
create index IDX_BSS_EDUCATIONAL_ORGANIZATION_ON_DIRECTOR on BSS_EDUCATIONAL_ORGANIZATION (DIRECTOR_ID)^
create index IDX_BSS_EDUCATIONAL_ORGANIZATION_ON_REGION on BSS_EDUCATIONAL_ORGANIZATION (REGION_ID)^
create index IDX_BSS_EDUCATIONAL_ORGANIZATION_ON_AREA on BSS_EDUCATIONAL_ORGANIZATION (AREA_ID)^
create index IDX_BSS_EDUCATIONAL_ORGANIZATION_ON_CITY on BSS_EDUCATIONAL_ORGANIZATION (CITY_ID)^
create index IDX_BSS_EDUCATIONAL_ORGANIZATION_ON_SUB_CITY on BSS_EDUCATIONAL_ORGANIZATION (SUB_CITY_ID)^
-- end BSS_EDUCATIONAL_ORGANIZATION
