-- begin BSS_QUASAR_PROJECT
alter table BSS_QUASAR_PROJECT add constraint FK_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE foreign key (BUSINESS_TYPE_ID) references BSS_BUSINESS_TYPE(ID)^
create unique index IDX_BSS_QUASAR_PROJECT_UK_PROJECT_NAME on BSS_QUASAR_PROJECT (PROJECT_NAME) where DELETE_TS is null ^
create index IDX_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE on BSS_QUASAR_PROJECT (BUSINESS_TYPE_ID)^
-- end BSS_QUASAR_PROJECT
-- begin BSS_MAIN_DIRECTION
create unique index IDX_BSS_MAIN_DIRECTION_UK_DIRECTION_NAME on BSS_MAIN_DIRECTION (DIRECTION_NAME) where DELETE_TS is null ^
-- end BSS_MAIN_DIRECTION
-- begin BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK
alter table BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_QUAPROQUAPRO_ON_QUASAR_PRODUCT_1 foreign key (QUASAR_PRODUCT_1_ID) references BSS_QUASAR_PRODUCT(ID)^
alter table BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK add constraint FK_QUAPROQUAPRO_ON_QUASAR_PRODUCT_2 foreign key (QUASAR_PRODUCT_2_ID) references BSS_QUASAR_PRODUCT(ID)^
-- end BSS_QUASAR_PRODUCT_QUASAR_PRODUCT_LINK
