alter table BSS_FEATURE add constraint FK_BSS_FEATURE_ON_PARENT_FEATURE foreign key (PARENT_FEATURE_ID) references BSS_FEATURE(ID);
alter table BSS_FEATURE add constraint FK_BSS_FEATURE_ON_PRODUCT foreign key (PRODUCT_ID) references BSS_QUASAR_PRODUCT(ID);
create index IDX_BSS_FEATURE_ON_PARENT_FEATURE on BSS_FEATURE (PARENT_FEATURE_ID);
create index IDX_BSS_FEATURE_ON_PRODUCT on BSS_FEATURE (PRODUCT_ID);
