alter table BSS_QUASAR_PROJECT add constraint FK_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE foreign key (BUSINESS_TYPE_ID) references BSS_BUSINESS_TYPE(ID);
create unique index IDX_BSS_QUASAR_PROJECT_UK_PROJECT_NAME on BSS_QUASAR_PROJECT (PROJECT_NAME) where DELETE_TS is null ;
create index IDX_BSS_QUASAR_PROJECT_ON_BUSINESS_TYPE on BSS_QUASAR_PROJECT (BUSINESS_TYPE_ID);
