alter table BSS_COMPETITOR_PRODUCT add constraint FK_BSS_COMPETITOR_PRODUCT_ON_COMPETITOR foreign key (COMPETITOR_ID) references BSS_COMPETITOR(ID);
create index IDX_BSS_COMPETITOR_PRODUCT_ON_COMPETITOR on BSS_COMPETITOR_PRODUCT (COMPETITOR_ID);
