alter table BSS_MARKET_SEGMENT add constraint FK_BSS_MARKET_SEGMENT_ON_BUSINESS_TYPE foreign key (BUSINESS_TYPE_ID) references BSS_BUSINESS_TYPE(ID);
create index IDX_BSS_MARKET_SEGMENT_ON_BUSINESS_TYPE on BSS_MARKET_SEGMENT (BUSINESS_TYPE_ID);
